language: python
python: 3.6
sudo: required
services: docker
before_install: 
    - "chmod +x install.sh"
    - "./install.sh"
script: "python3 -m tests.func_wallet_test; ./net_test.sh; sleep 8"
after_script: "./tn"
notifications:
   webhooks:
     urls:
       - https://integrations.bonbotics.io/travis/webhook/sOjyWg9ZB2dxRyJTazGE6CgIQpQQWCpga2VO8tIPbfU
     on_success: always
     on_failure: always
     on_start: never
